### ISSUE TITLE
Issue in logging out from device via telnet

### ISSUE THREAD

**Issue by Jainpriyal** [Juniper/py-junos-netconify#42]
I am trying to load config file via telnet from management port. Its loading file successfully but giving error while logging out from device.

```
(venv)sh-3.2# netconify --telnet=10.221.141.239,23 -f file.config -u foo -P abc123
TTY:login:connecting to TTY:10.221.141.239:23 ...
TTY:login:logging in ...
TTY:login:starting NETCONF
conf:loading into device ...
TTY:logout:logging out ...
ERROR:None


Traceback (most recent call last):
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/bin/netconify", line 6, in <module>
    results = nc.run()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/cmdo.py", line 238, in run
    self._hook_exception('ERROR', "{0}\n".format(str(logout_err)))
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/cmdo.py", line 236, in run
    self._tty_logout()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/cmdo.py", line 304, in _tty_logout
    self._tty.logout()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty.py", line 115, in logout
    self._logout_state_machine()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty.py", line 150, in _logout_state_machine
    self._logout_state_machine(attempt=attempt + 1)
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty.py", line 150, in _logout_state_machine
    self._logout_state_machine(attempt=attempt + 1)
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty.py", line 144, in _logout_state_machine
    _ev_tbl[found]()
KeyError: None
```

**Comment by Jainpriyal** [comment]
It loading configs in device but not committing it.
```
root@R1_re0> show configuration system services    

root@R1_re0> configure 
Entering configuration mode
The configuration has been changed but not committed

[edit]
root@R1_re0# show | compare    
[edit system services]
+    netconf {
+        ssh;
+    }

[edit]
root@R1_re0# exit 
The configuration has been changed but not committed
Exit with uncommitted changes? [yes,no] (yes) 
```

**Comment by vnitinv** [comment]
https://github.com/Juniper/py-junos-netconify/issues/46#issuecomment-249655221
