### ISSUE TITLE
Unable to load configuration in device via telnet using console ip and console port

### ISSUE THREAD

**Issue by Jainpriyal** [Juniper/py-junos-netconify#43]
I am trying to connect to console mode of device via telnet and load some configuration in device. But it is getting hanged after loading. 
I am using VMX.

```
(venv)sh-3.2# netconify --telnet=iec-en-pod4-vhost89.englab.juniper.net,17156 -f file.config -u foo -P pqr123
TTY:login:connecting to TTY:iec-en-pod4-vhost89.englab.juniper.net:17156 ...
TTY:login:logging in ...
TTY:login:starting NETCONF
conf:loading into device ...




^CTraceback (most recent call last):
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/bin/netconify", line 6, in <module>
    results = nc.run()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/cmdo.py", line 233, in run
    self._do_actions()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/cmdo.py", line 334, in _do_actions
    self._push_config()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/cmdo.py", line 415, in _push_config
    rc = self._tty.nc.load(**load_args)
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty_netconf.py", line 75, in load
    rsp = self.rpc(etree.tostring(cmd))
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty_netconf.py", line 164, in rpc
    rsp = self._receive()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty_netconf.py", line 175, in _receive
    line = self._tty.read().strip()
  File "/Users/jpriyal/Desktop/developement/netconify_pyEz/venv/lib/python2.7/site-packages/netconify/tty_telnet.py", line 74, in read
    return self._tn.read_until('\n', self.EXPECT_TIMEOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 296, in read_until
    return self._read_until_with_select(match, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 364, in _read_until_with_select
    while not self.eof and select.select(*s_args) == s_reply:
KeyboardInterrupt
```

**Comment by vnitinv** [comment]
https://github.com/Juniper/py-junos-netconify/issues/46#issuecomment-249655221
