### ISSUE TITLE
Issue in gathering facts from device, logout error [using telnet]

### ISSUE THREAD

**Issue by Jainpriyal** [Juniper/py-junos-netconify#46]
When I am trying gather facts from device, it is successfully collecting all facts but giving error while logging off from device.

```
(venv)sh-3.2# netconify --telnet 10.221.133.210,23 -u demo -P demo123 --facts
TTY:login:connecting to TTY:10.221.133.210:23 ...
TTY:login:logging in ...
TTY:login:starting NETCONF
facts:retrieving device facts...
facts:saving: ./R1_re01-facts.json
inventory:saving: ./R1_re01-inventory.xml
TTY:logout:logging out ...
ERROR:None

Traceback (most recent call last):
  File "/usr/local/bin/netconify", line 6, in <module>
    results = nc.run()
  File "/Library/Python/2.7/site-packages/netconify/cmdo.py", line 250, in run
    self._hook_exception('logout', err)
  File "/Library/Python/2.7/site-packages/netconify/cmdo.py", line 248, in run
    self._tty_logout()
  File "/Library/Python/2.7/site-packages/netconify/cmdo.py", line 304, in _tty_logout
    self._tty.logout()
  File "/Library/Python/2.7/site-packages/netconify/tty.py", line 115, in logout
    self._logout_state_machine()
  File "/Library/Python/2.7/site-packages/netconify/tty.py", line 150, in _logout_state_machine
    self._logout_state_machine(attempt=attempt + 1)
  File "/Library/Python/2.7/site-packages/netconify/tty.py", line 150, in _logout_state_machine
    self._logout_state_machine(attempt=attempt + 1)
  File "/Library/Python/2.7/site-packages/netconify/tty.py", line 144, in _logout_state_machine
    _ev_tbl[found]()
KeyError: None
```

**Comment by SimonXantaro** [comment]
I have the same problem.

**Comment by vnitinv** [comment]
@SimonXantaro You should use PyEZ 2 for this . Refer example
https://github.com/Juniper/junosautomation/blob/master/pyez/PyEZ_2_0_0.ipynb

```python
from jnpr.junos import Device
from lxml import etree

with Device(host='10.xxx.1.xxx', user='xxx', password='xxxx', mode='telnet', port='23', gather_facts=True) as dev:
    print dev.facts
```
